#!/bin/bash

grep -w AM 0310_Dealer_schedule 0312_Dealer_schedule 0315_Dealer_schedule | grep 05 | grep 0310 | awk '{print $1, $2, $5, $6}' >> Dealers_working_during_losses

grep -w AM 0310_Dealer_schedule 0312_Dealer_schedule 0315_Dealer_schedule | grep 08 | grep 0310 | awk '{print $1, $2, $5, $6}' >> Dealers_working_during_losses

grep -w PM 0310_Dealer_schedule 0312_Dealer_schedule 0315_Dealer_schedule | grep 02 | grep 0310 | awk '{print $1, $2, $5, $6}' >> Dealers_working_during_losses

grep -w PM 0310_Dealer_schedule 0312_Dealer_schedule 0315_Dealer_schedule | grep 08 | grep 0310 |  awk '{print $1, $2, $5, $6}' >> Dealers_working_during_losses

grep -w PM 0310_Dealer_schedule 0312_Dealer_schedule 0315_Dealer_schedule | grep 11 | grep 0310 | awk '{print $1, $2, $5, $6}' >> Dealers_working_during_losses

grep -w AM 0310_Dealer_schedule 0312_Dealer_schedule 0315_Dealer_schedule | grep 05 | grep 0312| awk '{print $1, $2, $5, $6}' >> Dealers_working_during_losses

grep -w AM 0310_Dealer_schedule 0312_Dealer_schedule 0315_Dealer_schedule | grep 08 | grep 0312 | awk '{print $1, $2, $5, $6}' >> Dealers_working_during_losses

grep -w PM 0310_Dealer_schedule 0312_Dealer_schedule 0315_Dealer_schedule | grep 02 | grep 0312 | awk '{print $1, $2, $5, $6}' >> Dealers_working_during_losses

grep -w PM 0310_Dealer_schedule 0312_Dealer_schedule 0315_Dealer_schedule | grep 08 | grep 0312 | awk '{print $1, $2, $5, $6}' >> Dealers_working_during_losses

grep -w PM 0310_Dealer_schedule 0312_Dealer_schedule 0315_Dealer_schedule | grep 11 | grep 0312 |  awk '{print $1, $2, $5, $6}' >> Dealers_working_during_losses

grep -w AM 0310_Dealer_schedule 0312_Dealer_schedule 0315_Dealer_schedule | grep 05 | grep 0315 | awk '{print $1, $2, $5, $6}' >> Dealers_working_during_losses

grep -w AM 0310_Dealer_schedule 0312_Dealer_schedule 0315_Dealer_schedule | grep 08 | grep 0315 | awk '{print $1, $2, $5, $6}' >> Dealers_working_during_losses

grep -w PM 0310_Dealer_schedule 0312_Dealer_schedule 0315_Dealer_schedule | grep 02 | grep 0315 | awk '{print $1, $2, $5, $6}' >> Dealers_working_during_losses


